name: Update AU Product Review Feed

on:
  schedule:
    - cron: '0 3 * * *'  # Runs every day at 3 AM UTC
  workflow_dispatch:

jobs:
  update-au-feed:
    runs-on: ubuntu-latest

    steps:
      - name: Download NZ Okendo XML Feed
        run: |
          curl -s https://prod-1-reviews-product-reviews-feed.s3.amazonaws.com/5880440a-4a9e-4974-b370-540ebb2d6273/google-product-reviews-feed.xml -o nz-feed.xml
          sed 's/dwights.co.nz/dwights.com.au/g' nz-feed.xml > au-feed.xml

      - name: Write GCP service account key
        run: echo "${{ secrets.GCP_KEY }}" | base64 --decode > gcp-key.json
        env:
          GCP_KEY: ${{ secrets.GCP_KEY }}

      - name: Upload AU feed to Google Cloud Storage
        uses: google-github-actions/upload-cloud-storage@v1
        with:
          path: ./au-feed.xml
          destination: dwightsokendoaufeed/google-product-reviews-au.xml/google-au-product-reviews-2025.xml
        env:
          GOOGLE_APPLICATION_CREDENTIALS: gcp-key.json
