name: Update Okendo AU Feed

on:
  schedule:
    - cron: '0 3 * * *'  # Runs daily at 3am UTC
  workflow_dispatch:

jobs:
  update-feed:
    runs-on: ubuntu-latest

    steps:
      - name: Download and modify XML
        run: |
          curl -s https://prod-1-reviews-product-reviews-feed.s3.amazonaws.com/5880440a-4a9e-4974-b370-540ebb2d6273/google-product-reviews-feed.xml -o feed.xml
          sed -i 's/dwights.co.nz/dwights.com.au/g' feed.xml
          head -n 5 feed.xml

      - name: Write GCP service account key
        run: echo "${{ secrets.GCP_KEY }}" | base64 --decode > gcp-key.json

      - name: Install gcloud CLI
        run: |
          sudo apt-get update -y
          sudo apt-get install -y curl apt-transport-https ca-certificates gnupg
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
          sudo apt-get update -y && sudo apt-get install -y google-cloud-sdk

      - name: Authenticate and upload to GCS
        run: |
          gcloud auth activate-service-account --key-file=gcp-key.json
          gcloud config set project dwights-okendo-au-feed
          gsutil cp feed.xml gs://dwightsokendoaufeed/google-product-reviews-au.xml
          gsutil ls gs://dwightsokendoaufeed
