name: Update Okendo AU Feed

on:
  schedule:
    - cron: '0 3 * * *'  # Runs daily at 3am UTC
  workflow_dispatch: {}  # Allows manual trigger

jobs:
  update-feed:
    runs-on: ubuntu-latest

    steps:
      - name: Download Okendo NZ XML
        run: |
          curl -s https://prod-1-reviews-product-reviews-feed.s3.amazonaws.com/5880440a-4a9e-4974-b370-540ebb2d6273/google-product-reviews-feed.xml -o feed.xml
          sed -i 's/dwights.co.nz/dwights.com.au/g' feed.xml

      - name: Upload to Google Cloud Storage
        uses: google-github-actions/upload-cloud-storage@v1
        with:
          path: ./feed.xml
          destination: dwightsokendoaufeed/google-product-reviews-au.xml
          parent: false
          process_gcloudignore: false
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_KEY }}
