name: Update Okendo AU Feed

on:
  schedule:
    - cron: '0 3 * * *'  # Daily at 3am UTC
  workflow_dispatch: {}

jobs:
  update-feed:
    runs-on: ubuntu-latest

    steps:
      - name: Download Okendo NZ XML
        run: |
          curl -s https://prod-1-reviews-product-reviews-feed.s3.amazonaws.com/5880440a-4a9e-4974-b370-540ebb2d6273/google-product-reviews-feed.xml -o feed.xml
          sed -i 's/dwights.co.nz/dwights.com.au/g' feed.xml

      - name: Confirm feed.xml exists and show preview
        run: |
          if [ ! -f "feed.xml" ]; then
            echo "❌ feed.xml not found"
            exit 1
          fi
          echo "✅ feed.xml found. Preview:"
          head -n 5 feed.xml

      - name: Write GCP service account key to file
        run: |
          echo "$GCP_KEY" | base64 --decode > gcp-key.json
        env:
          GCP_KEY: ${{ secrets.GCP_KEY }}

      - name: Authenticate with GCP
        run: |
          gcloud auth activate-service-account --key-file=gcp-key.json
          gcloud config set project dwights-okendo-au-feed

      - name: Upload feed.xml to Google Cloud Storage
        run: |
          gsutil cp feed.xml gs://dwightsokendoaufeed/google-product-reviews-au.xml

      - name: Debug: List files in GCS bucket
        run: |
          gsutil ls gs://dwightsokendoaufeed
